[package]
name = "examples"
edition = "2024"
version = "0.0.1"

[workspace]
members = ["./packages/vex-v5-serial", "./packages/vex-cdc"]
resolver = "3"

[workspace.dependencies]
vex-v5-serial = { version = "0.5.1", path = "packages/vex-v5-serial" }
vex-cdc = { version = "0.1.0", path = "packages/vex-cdc" }

[dev-dependencies]
vex-v5-serial = { workspace = true, features = [
    "file-commands",
    "screen-commands",
] }
log = "0.4.28"
smol = "2.0.2"
smol-macros = "0.1.1"
macro_rules_attribute = "0.2.3"
simplelog = "0.12.2"
rustyline = "14.0.0"
