[package]
name = "vex-v5-serial"
version = "0.5.1"
edition = "2024"
license = "MIT"
description = "A library for communicating with VEX V5 Brains."
repository = "https://github.com/vexide/vex-v5-serial"
authors = ["vexide", "Gavin Niederman <gavinniederman@gmail.com>", "Tropical"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We depend on this because for some reason it fixes an issue with tokio-serial.
vex-cdc = { workspace = true }
log = "0.4.28"
thiserror = "2"
flate2 = "1.1.2"

tokio = { version = "1.47.1", features = [
    "io-util",
    "macros",
], optional = true }
tokio-serial = { version = "5.4.5", default-features = false, optional = true }
tokio-stream = { version = "0.1.17", default-features = false, optional = true }
serialport = { version = "4.7.3", optional = true, features = [
    "usbportinfo-interface",
] }
btleplug = { version = "0.11.5", optional = true }
futures = { version = "0.3.30", default-features = false, optional = true }
uuid = { version = "1.8.0", default-features = false, optional = true}
image = { version = "0.25.1", default-features = false, optional = true }

[features]
default = ["serial", "bluetooth"]
serial = ["dep:tokio", "dep:tokio-serial", "dep:serialport"]
bluetooth = [
    "dep:tokio",
    "dep:tokio-stream",
    "dep:btleplug",
    "dep:futures",
    "dep:uuid",
]
screen-command = ["dep:image"]
